### Importing relevant libraries

In [4]:
import os
import requests
import pandas as pd

__________________________

### Solar Power Generation Trends (Monthly) NITI 2015 - 2026

In [5]:
url = 'https://icedapi.niti.gov.in/v1/gen-metatable-data'

headers = {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-GB,en;q=0.9",
    "content-type": "application/json",
    "origin": "https://iced.niti.gov.in",
    "priority": "u=1, i",
    "referer": "https://iced.niti.gov.in/",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/153.0.0.0 Safari/537.36"
}

payload = {
    "source": "solar",
    "rangeType": "monthly"
}

# Path to store the raw csv
raw_path = "../data/raw/niti_aayog/solar-gen-trends-15to26.csv"


# Only trigger API call if local file doesn't exist
if not os.path.exists(raw_path):
    print(f'Fetching generation dataset from NITI')
    response = requests.post(
        url=url, 
        headers=headers, 
        json=payload
    )

    print(f'Status code: {response.status_code}')

    gen_data = response.json()

    #Checking if the fetched data is a list
    if isinstance(gen_data, list):
        gen_df = pd.DataFrame(gen_data)

    gen_df.to_csv('../data/raw/niti_aayog/solar-gen-trends-15to26.csv', index=False)

else: 
    print(f'Dataset already exists at {raw_path}. Skipping API request...')


gen_df

Dataset already exists at ../data/raw/niti_aayog/solar-gen-trends-15to26.csv. Skipping API request...

     source                        state  generation     year      month
0     solar  Andaman and Nicobar Islands        1.17  2015-16      April
1     solar  Andaman and Nicobar Islands        0.83  2015-16     August
2     solar  Andaman and Nicobar Islands        0.84  2015-16   December
3     solar  Andaman and Nicobar Islands        1.37  2015-16   February
4     solar  Andaman and Nicobar Islands        1.35  2015-16    January
...     ...                          ...         ...      ...        ...
5251  solar                  West Bengal        0.00  2026-27      March
5252  solar                  West Bengal       47.38  2026-27        May
5253  solar                  West Bengal        0.00  2026-27   November
5254  solar                  West Bengal        0.00  2026-27    October
5255  solar                  West Bengal        0.00  2026-27  September

[5256 rows x 5 columns]

__________________________

### Solar Power Installed Capacity Trends (Yearly) NITI 2015 - 2026

In [6]:
url = "https://icedapi.niti.gov.in/v1/capacity-metatable-data?switchMetaData=false"

headers = {
    "accept" : "application/json, text/plain, */*",
    "accept-language": "en-GB, en; q=0.9",
    "dnt": "1", 
    "origin": "https://iced.niti.gov.in", 
    "referer": "https://iced.niti.gov.in/", 
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/153.0.0.0 Safari/537.36"
}

raw_path = "../data/raw/niti_aayog/solar-installed-capacity-trends-15to26.csv"

# Only trigger API call if local file doesn't exist
if not os.path.exists(raw_path):
    print(f'Fetching capacity dataset from NITI')

    response = requests.get(url=url, headers=headers)

    print(f'Status code: {response.status_code}')

    capacity_data = response.json()
     #Checking if the fetched data is a list
    if isinstance(capacity_data, list):
        capcity_df = pd.DataFrame(capacity_data)

    capcity_df = capcity_df[capcity_df['source'].str.strip() =='solar']
    capcity_df.to_csv('../data/raw/niti_aayog/solar-installed-capacity-trends-15to26.csv', index=False)

else: 
    print(f'Dataset already exists at {raw_path}. Skipping API request...')

    
capcity_df

Fetching capacity dataset from NITI
Status code: 200

                            state    fyear source  capacity
1     Andaman and Nicobar Islands  2015-16  solar      5.34
4     Andaman and Nicobar Islands  2016-17  solar      6.80
7     Andaman and Nicobar Islands  2017-18  solar      6.80
10    Andaman and Nicobar Islands  2018-19  solar     11.97
13    Andaman and Nicobar Islands  2019-20  solar     12.43
...                           ...      ...    ...       ...
2015                  West Bengal  2022-23  solar    179.98
2021                  West Bengal  2023-24  solar    194.07
2027                  West Bengal  2024-25  solar    320.62
2032                  West Bengal  2025-26  solar    320.62
2037                  West Bengal  2026-27  solar    363.50

[438 rows x 4 columns]